name: Production Build
on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: |
          cd ./frontend && yarn install
      - name: Production Build
        run: |
          cd ./frontend && yarn build
